host: 127.0.0.1
port: 5678
providers:
    mtranserver:
        enable: true
        endpoints:
            - http://192.168.0.100:8989
            - http://192.168.0.101:8989
    google:
        enable: false
        proxy: http://127.0.0.1:7890 